@startuml

partition 自宅サーバー {
  (*) --> n分待機
  --> "kintoneアプリにアクセス"
  note right : ヘッドレスブラウザーを使用。
}
partition kintone {
  "kintoneアプリにアクセス" --> "リソースのURLへの疎通確認"
  --> "結果の保存"
  if "疎通結果" then
    -->[true] (*)
  else
    if "アラートflg" then
      -->[true] "アラートカウンターをインクリメント"
      if "しきい値を超えている" then
        --> [true] "アラート"
        --> "アラートカウンターを0にリセット"
        --> (*)
      else
        -->[false] (*)
      endif
    else
      -->[false] (*)
    endif
  endif
}
@enduml